# Generated by Django 5.2.5 on 2025-09-11 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pml_app', '0003_admin_help_manager_project_task_teammember_and_more'),
        ('pml_app', '0003_existing_tables'),
    ]

    operations = [
    ]
