# Generated by Django 5.2.5 on 2025-09-11 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pml_app', '0004_merge_20250911_1048'),
    ]

    operations = [
        migrations.AddField(
            model_name='help',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='help',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in-progress', 'In Progress'), ('resolved', 'Resolved')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='help',
            name='description',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
