# Generated by Django 5.2.5 on 2025-09-11 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pml_app', '0005_help_created_at_help_status_alter_help_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='help',
            name='status',
        ),
    ]
