# Generated by Django 5.2.5 on 2025-09-15 11:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pml_app', '0006_remove_help_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectTeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pml_app.project')),
                ('team_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pml_app.teammember')),
            ],
            options={
                'db_table': 'project_team_members',
                'unique_together': {('project', 'team_member')},
            },
        ),
    ]
