# Generated by Django 5.2.5 on 2025-09-18 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pml_app', '0009_project_deadline_project_progress'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammember',
            name='position',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]