# Generated by Django 5.2.5 on 2025-09-18 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pml_app', '0010_teammember_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('in_progress', 'In Progress'), ('completed', 'Completed')], default='in_progress', max_length=20),
        ),
    ]